# Variables that contains the user credentials to access Twitter API 
ACCESS_TOKEN = '3190786043-SSvDKjJZBtFw2yC64HOlade3AUC18thW2O2cuQc'
ACCESS_SECRET = 'VOndBmNyoYJ3DIQRFGnbHCEPrZt7JQvrioW2eDujbLkVp'
CONSUMER_KEY = '2jUAOcmZ5Rb4Cigyv7VloGbhw'
CONSUMER_SECRET = 'YXBvTuTrBY3d6RjdHIl9oHJYkwVcTQv129XpyiySVZBbUGtn40'
IBM_WATSON_API_KEY = 'VYB0mPzErWYlSzOZtleNE1hWGFC_dHdhByjNLrPmjH2V'
